eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/

microservice:
  payment-service:
    endPoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/api/payments/
  user-service:
    endPoints:
      fetchUserById:
        uri: http://USER-SERVICE/api/users/

logging:
  file:
    name: E:/java_learning/javatechie/masterclass_ms/ms-boot/app-logs/ecom-logs.log        
      
